### ISSUE TITLE
Unloading of workers (and hence Platform Collector)

### ISSUE THREAD

**Issue by kenchris** [WICG/compute-pressure#104]
Find the right hooks to make sure we inform the platform collector when workers are unloaded

**Comment by kenchris** [comment]
Potentially relevant:

https://html.spec.whatwg.org/#suspendable-worker
https://html.spec.whatwg.org/#dom-workerglobalscope-closing

**Comment by kenchris** [comment]
This reminds me that the closing and unloading of the worker should be handled by garbage collection as we do in Generic Sensors:

> When a [Sensor](https://www.w3.org/TR/generic-sensor/#sensor) object whose [[[state]]](https://www.w3.org/TR/generic-sensor/#dom-sensor-state-slot) is "activated" or "activating" is garbage collected, the user agent must invoke [deactivate a sensor object](https://www.w3.org/TR/generic-sensor/#deactivate-a-sensor-object) with this object as argument.

**Comment by kenchris** [comment]
We probably want to handle suspension (bfcache, suspendable worker, non-fully active document). @rakuco does Generic Sensors handle that?

**Comment by kenchris** [comment]
Web Bluetooth has a note about disconnecting on garbage collection:

> Note: Disconnecting on garbage collection ensures that the UA doesn’t keep consuming resources on the remote device unnecessarily.

**Comment by rakuco** [comment]
Sorry for the delay here.

> @rakuco does Generic Sensors handle that? It seems to only send events to active documents (why not fully active?) so I assume that you still keep the platform sensors active while in bfcache etc

Support for the "fully active" concept is pending (see w3c/sensors#415). I believe bfcache is not a concern because sensors are stopped when the page is not visible, which is the case when a page is entering the bfcache if I recall correctly (that's the case for Screen Wake Lock in the Chromium implementation at least).

Although the spec says sensors are exposed to workers, the Blink implementation currently only exposes them to `Window`.

Does this help you?
