### ISSUE TITLE
Support the API in DedicatedWorker

### ISSUE THREAD

**Issue by kenchris** [WICG/compute-pressure#15]
Broken out from https://github.com/WICG/compute-pressure/issues/14

**Comment by kenchris** [comment]
Hi @fideltian, if Zoom can list the use-cases you have for this, that would be very welcome!

**Comment by fideltian** [comment]
Hi kenChris, Thanks for creating a seperate issue. The computing work are mostly done in worker thread. it is better the worker could get the data direclty. otherwise, main thread need to post the data to all workers.

And i do think different worker(audio or video processing) could set different threashhold of cpu. It means they could set mulitiple observers. it will easier for each type of worker to handling the work related with cpu estimation.

**Comment by kenchris** [comment]
If you have multiple workers with different thresholds then you can send the data back to main thread and join the data for more precise readings - basically working around the privacy advantages of using buckets.
